### ISSUE TITLE
An updated set of Lite data is available for download every few weeks

### ISSUE THREAD

**Issue by chrsoo** [51Degreesmobi/51Degrees.mobi-Lite-Binary#1]
> Lite Device Data can be used free of charge. It does not contain the very newest mobile devices (handsets released in the previous three months) and does not include as many properties as the Premium version. **An updated set of Lite data is available for download every few weeks.** You can always find the latest Lite device data file at our github repository.

[51Degrees.com](https://51degrees.com/support/faqs/device-data)

As of writing, last commit was 11 months ago.

**Comment by Joseph51D** [comment]
Hi, As of version 3.2 of the 51Degrees API we include the binary data file in the API repositories. You can find the new data files in [C](https://github.com/51Degrees/Device-Detection), [Java](https://github.com/51Degrees/Java-Device-Detection) & [.NET](https://github.com/51Degrees/dotNET-Device-Detection)

**Comment by chrsoo** [comment]
OK, looks like the link on the 51Degrees website has been fixed and this repository has now been marked as "depreciated" although I think you may want to change it to "deprecated"... ;-) Thanks!
